### ISSUE TITLE
建议提供一个demo

### ISSUE THREAD

**Issue by Mscynol** [mediaios/net-diagnosis#1]
建议提供一个demo

**Comment by mediaios** [comment]
你好，非常感谢你的建议。我把`NetPinger`在SDK中开源了，地址是https://github.com/mediaios/net-diagnosis/tree/master/NetPinger(代码有点糙，还没做具体优化)  如果后续有什么问题，欢迎在此提出。

**Comment by mediaios** [comment]
README里也对此次更新有说明。
